all:
	g++ -c libreria.cpp
	g++ -c ejercicio1.cpp
	g++ -o ejecutable libreria.o ejercicio1.o
	./ejecutable

eliminar:
	rm *.o

ejecutar:
	./ejecutable

crear:
	mkdir carpeta

eliminarCarpeta:

crearArchivo: